allenai/mmda

examples/vila_for_scidoc_parsing/README.md, examples/vila_for_scidoc_parsing/main.py, examples/vila_for_scidoc_parsing/requirements.txt, mmda/predictors/hf_predictors/utils.py, mmda/predictors/hf_predictors/vila_predictor.py, mmda/predictors/lp_predictors.py, setup.py
Previously, LP predictor returns the absolute coordinates, which is incompatible with the rest of the library. In this update, 
1. LP predictor returns the relative coordinates
2. Fix the coordinate conversion for VILA models 
3. Update the VILA example to incorporate main mmda updates
=> [fix] Return relative coordinates in LP predictor

mmda/parsers/grobid_parser.py, mmda/parsers/parser.py, mmda/parsers/pdfplumber_parser.py, mmda/parsers/symbol_scraper_api.py, mmda/parsers/symbol_scraper_parser.py, mmda/rasterizers/rasterizer.py, mmda/types/document.py, mmda/types/image.py, services/parsers/symbolscraper/model/predictor.py
1. Rasterizer handles PDF->Image.  It's separate from Parser.
2. Remove dpi=72 default value.
3. Clean up PIL.Image import names to be less confusing
4. Update library tests
5. Update SScraper predictor service to use Rasterizer
=> [wip] Move PDF->Image functionality *out* of Parser into Rasterizer

mmda/predictors/hf_predictors/vila_predictor.py, mmda/types/document.py
To avoid timeouts when calling VILA, ScienceParsePlus needs to split large documents into fixed-page-length. It does this by filtering the tokens and blocks to a given page range. Change the VILA predictor to tolerate pages that have no tokens. This is probably possible in general anyway, for example if a PDF has a full-page image.
SPP breaks up the document by keeping the full symbols string, image list, and page annotations. It would be more space efficient to replace the symbols with the sub-range that applies to the pages being sent, and adjusting all of the span offsets. That's still possible, but I'll leave that to a future optimization.
Also, https://github.com/allenai/mmda/pull/62 broke the `document.from_json()` method. I guess there are no tests that would catch that? This PR …
=> Skip pages with no tokens

examples/bibliography_extraction/main.py, mmda/types/annotation.py, mmda/types/document.py, mmda/types/user_data.py, tests/test_predictors/test_dictionary_word_predictor.py, tests/test_types/test_span_group.py
An idea... Not my favorite but the branch [types-nouveau](https://github.com/allenai/mmda/tree/types-nouveau) refactoring would take very long to roll out to all the created predictors, etc. Please reference that branch for the original idea (a layer of typing).
Annotations are always stored on the top-level document with a special key when nested.
1. [x] Tests need fixing ... 
2. [x] Examples need fixing ...
3. [x] Deeply nested annotations can have ID conflict easily
Example JSON format:
```json
{
"symbols":"This is a test document!",
"tokens":[
{
"spans":[
{
"start":0,
"end":4
},
{
"start":5,
"end":7
}
],
"id":1,
"uuid":"997031e4-bbb5-4216-ace7-a88e410df7af"
}
],
"SpanGroup|997031e4-bbb5-4216-ace7-a88e410df7af|capitalized":[
{
"spans":[
{
"start":0,
"end":4
},
{
"start":5,
"end":7
}
], …
```
=> Allow nested annotations on a span group

mmda/parsers/pdfplumber_parser.py
we are getting some PdfPlumber errors like [this](https://app.datadoghq.com/logs?query=source%3Aspp%20env%3Aprod%20status%3A%28error%20OR%20critical%20OR%20info%29&cols=service&event=AQAAAX9L3ZOrltRcPQAAAABBWDlMM2FCWkFBQTFTNTByM1NKT1lBQUI&index=main&integration_id=&integration_short_name=&messageDisplay=inline&saved_view=750965&stream_sort=desc&viz=stream&from_ts=1646245258312&to_ts=1646245320495&live=false) in the scienceparseplus project:
```
File "/usr/local/lib/python3.8/site-packages/mmda/parsers/pdfplumber_parser.py", line 158, in parse
doc = self._load_pdf_as_doc(input_pdf_path)
File "/usr/local/lib/python3.8/site-packages/mmda/parsers/pdfplumber_parser.py", line 297, in _load_pdf_as_doc
doc_json = self._convert_nested_text_to_doc_json(page_to_line_to_tokens)
File …
```
=> PdfPlumber: fix for if page has no tokens

mmda/parsers/pdfplumber_parser.py, mmda/types/box.py, tests/test_parsers/test_grobid_header_parser.py
Sometimes PDF Parsers will return token coordinates with negative or extra large values (larger than the page_width/height). This is not a bug but a feature designed in the "printing commands" of PDF grammars. However, this will break our models and many downstream processing. 
This issue aims to fix this issue via adding additional checks for PDFPlumber Parsers. It brings similar clipping functions in the VILA repo https://github.com/allenai/VILA/blob/6a5c6783b75eefaeaed01b67bc3be025add9cde3/src/vila/pdftools/pdfplumber_extractor.py#L204 to the mmda PDFPlumberParsers to increase the robustness of token parsers. 
Some examples: 
Previously a token will have a box like (the box is outside the page range)
```python
box=Box(l=0.10764222310323279, t=-0.35593721269999645, …
```
=> Additional checks for pdfplumber parser

mmda/predictors/hf_predictors/utils.py
From earlier testing, I remember that `convert_document_page_to_pdf_dict` takes a significant fraction of the total prediction time for vila. Here's a simple change that does all the work in a single iteration over tokens instead of multiple list comprehensions. I tested this on some production PDFs and saw a 3x speed-up.
@cmwilhelm 
@yoganandc 
https://github.com/allenai/scholar/issues/32695
=> Speed up vila pre-processing

setup.py
Unbounded upper version was pulling in breaking
changes transitively in builds.
=> Pins vila to 0.3.0.

examples/vila_for_scidoc_parsing/main.py
Example was a little bit out of date because it did not use `PDF2ImageRasterizer`. Because of that, `LayoutParserPredictor` couldn't find any regions.
=> Updated example to use rasterizer APIs

mmda/types/indexers.py, setup.py
Deduplication logic was causing big slow-down in
real world deployments of MMDA models.
The current changeset uses object id to do set
membership checks instead of list membership checks.
Using production S2 data, this resulted in an approximately 400-fold
reduction in `indexers.py` latency for VILA, with identical
output to prior implementation.
Kudos to @Whattabatt both for the profiler tool
that identified the offending line and noticing the `not in`
was likely a linear operation.
=> use set membership instead of list membership

mmda/types/document.py, mmda/types/indexers.py, setup.py
A substantial fraction of our real-world runtime was going
into querying the IntervalTree we use for detecting
SpanGroup overlaps.
This changeset replaces IntervalTree with NCLS:
https://github.com/biocore-ntnu/ncls,
a library that came out of genomics sequence
analysis research.
Profiling results indicate this improves inference times
on real-world S2 documents in VILA by a further
~42%.
Note:
@kyleclo  this library is made available under
`BSD 3-Clause "New" or "Revised" License`.
I don't know how that intersects with the Apache
license in this project.
The author also requests citation in any academic
publication.
=> Replaces interval tree for ncls

mmda/types/document.py, setup.py
Speeds up VILA runtime by ~10%,
doesn't affect output.
=> Removes deepcopy from annotation method.

mmda/predictors/heuristic_predictors/sentence_boundary_predictor.py
As title suggests, this PR fixes a significant bug that resulted in sentences not being properly created. The issue was due to the fact that merged spans were incorrectly parsed as a uuid instead of span attribute when creating a `SpanGroup` object.
Beside the fix for the bug above, this PR also adds better handling of words when performing sentence segmentation: now, instead of using just the first symbol of a word/token, it uses the text attribute when available, and joins all symbols when not available.
=> Fix for `SpanGroup` creation in `PysbdSentenceBoundaryPredictor` that resulted in no sentences.

mmda/utils/tools.py, tests/test_utils/test_tools.py
minor PR: added tests for a pretty important functionality that was being used -- how to combine Spans that are next to each other into a single big Span.  the key thing that was undocumented was that Boxes for the underlying Spans actually disappear after this merging functionality, which the tests now capture.
dont think this is intended behavior we want to support in future, but for now, this is how this utility is being used
=> Kylel/2022 09/span group utils

mmda/types/document.py, setup.py, tests/test_types/test_document.py
Previously we would skip making attrs
on the document to represent these empty
annotation groups. This resulted in attr
not found errors in contexts where an expected
field was absent and legitimately empty.
=> Allows empty annotations.

mmda/predictors/hf_predictors/mention_predictor.py, setup.py
should fix the issue where `MentionPredictor` was mutating fields in the document. See code below; the final Assertion failed prior to this PR.
Consequence of this is that we would observe `doc.tokens` where the `token` is very long (e.g. `token == 'Yang et al'`) instead of just `token == 'Yang'`)
```
pdfpath = '/Users/kylel/ai2/mmda/data/from_bailey/121e30c48546e671dc5e16c694c5e69b392cf8fb.pdf'
doc = parser.parse(input_pdf_path=pdfpath)
tokens1 = [''.join(t.symbols) for t in doc.tokens]
images = rasterizer.rasterize(input_pdf_path=pdfpath, dpi=72)
doc.annotate_images(images=images)
tokens2 = [''.join(t.symbols) for t in doc.tokens]
box_groups = vision_predictor.predict(document=doc)
doc.annotate(blocks=box_groups)
tokens3 = [''.join(t.symbols) for t in doc.tokens]
vila_preds = …
```
=> Kylel/2022 10/hotfix mention detection

mmda/parsers/pdfplumber_parser.py, setup.py, tests/test_parsers/test_pdf_plumber_parser.py
Before, due to tokenization from PDF Plumber that would split on every punctuation, we were observing Documents contained symbols that looked like:
```
>> doc.symbols:
References Mitchell P . Marcus , Beatrice Santorini , and Mary Ann Marcinkiewicz . 1993 .
>> doc.tokens:
References
Mitchell
P
.
Marcus
,
Beatrice
Santorini
,
and
Mary
Ann
Marcinkiewicz
.
1993
.
```
This is because the way PDFPlumberParser constructs `.symbols` to include in Document was previously using either whitespace `" "` or newline `"\n"` concatenation of the strings in each detected token.
What we actually want is to keep this fine-grained partitioning of tokens, but to still have `.symbols` better preserve the  (lack of) whitespacing that exists in the original document, when appropriate. Ideally:
```
>> …
```
=> Kylel/2022 10/hotfix spacing in pdfplumber symbols

pyproject.toml, src/mmda/parsers/pdfplumber_parser.py, src/mmda/parsers/symbol_scraper_parser.py, src/mmda/predictors/d2_predictors/bibentry_detection_predictor.py, src/mmda/predictors/heuristic_predictors/dictionary_word_predictor.py, src/mmda/predictors/heuristic_predictors/grobid_citation_predictor.py, src/mmda/predictors/heuristic_predictors/sentence_boundary_predictor.py, src/mmda/predictors/hf_predictors/token_classification_predictor.py, src/mmda/predictors/hf_predictors/utils.py, src/mmda/predictors/hf_predictors/vila_predictor.py, src/mmda/predictors/lp_predictors.py, src/mmda/predictors/tesseract_predictors.py, src/mmda/types/document.py, src/mmda/types/names.py, tests/test_parsers/test_override.py, tests/test_types/test_document.py
Example use case: Store metadata about the PDF outline (i.e., table of contents sidebar) that doesn't fit perfectly into any of the existing annotation types (BoxGroup or SpanGroup). A PDF outline object is essentially a tuple of (text, location-pointer, nesting-level).
Idea discussed briefly with @kyleclo so this may need refinement.
=> Add Metadata as a top-level Document object

pyproject.toml, src/ai2_internal/api.py
sklearn is no longer a real package on pypi
and instead was a deprecation timebomb waiting to blow up.
See:
https://pypi.org/project/sklearn/
Must now install as "scikit-learn" for reasons.
* separately provides a default to some new parameter that was added on
`api.SapnGroup`, as we're not explicitly passing this
=> Fixes citation linker and errata

src/mmda/parsers/pdfplumber_parser.py
In exceptional cases this pdfplumber reference can be left open. Addresses ResourceWarning observed in tests.
=> [bug] Fix dangling file reference leading to ResourceWarning

pyproject.toml, src/mmda/predictors/heuristic_predictors/dictionary_word_predictor.py, tests/test_predictors/test_dictionary_word_predictor.py
Resolve this issue:
```
File "/usr/local/lib/python3.8/site-packages/mmda/predictors/heuristic_predictors/dictionary_word_predictor.py", line 149, in predict
token_id_to_word_id, word_id_to_text = self._predict_tokens(
File "/usr/local/lib/python3.8/site-packages/mmda/predictors/heuristic_predictors/dictionary_word_predictor.py", line 402, in _predict_tokens
assert None not in token_id_to_word_id.values()
AssertionError
```
Basically, found singletons with `-` hyphen that were breaking row logic. Those are classified correctly now.
=> Kylel/2022 12/debug dwp

pyproject.toml, src/mmda/predictors/heuristic_predictors/dictionary_word_predictor.py, tests/test_predictors/test_dictionary_word_predictor.py
Addressing problems in https://github.com/allenai/scholar/issues/34648. Both PDFs run fine now after this fix + previous version upgrade.
Also upgrade `necessary` which something changed in upstream dependency.
=> Kylel/2022 12/bugfix overlapping spans pdfplumber

pyproject.toml, src/ai2_internal/api.py, src/ai2_internal/citation_links/integration_test.py, src/ai2_internal/citation_links/interface.py
Purely additive change that has the citation linker
timo predictor return links in the future-standard
generalized `Relation` format.
This is the format expected by clients in new SPP
code.
cc also @geli-gel as this may be relevant for grobid
work
=> TIMO Citation linker returns Relations objects.

pyproject.toml, src/ai2_internal/citation_links/integration_test.py, src/mmda/predictors/xgb_predictors/citation_link_predictor.py
This would previously cause runtime error.
Right thing to do is to detect when we have no bibs, and predict nothing.
=> Handle no-bibs in citation linker.

pyproject.toml, src/mmda/utils/tools.py, tests/test_utils/test_tools.py
group Spans by pages when merging SpanGroup Spans by symbol distance to avoid "boxes are on different pages" error
This error is coming up when annotating Grobid BoxGroups onto a Document because some BoxGroups contain boxes across pages with spans that might be close together in symbol distance.
related to allenai/scholar/issues/35751
=> Merge Spans per page when merging spans by symbol distance

pyproject.toml, src/ai2_internal/bibentry_predictor_mmda/integration_test.py, src/mmda/predictors/hf_predictors/bibentry_predictor/predictor.py
RE: https://github.com/allenai/scholar/issues/35525
An empty list of bib entries is valid input for
the bib entry predictor. Previously we were blowing up.
Now we return an empty prediction set.
=> Bib entry predictor handles empty inputs

pyproject.toml, src/ai2_internal/bibentry_detection_predictor/integration_test.py, src/ai2_internal/bibentry_detection_predictor/interface.py
for allenai/scholar#36565
Removes span boxes from bib_entry SpanGroups, and turns raw_bib_entry_boxes from BoxGroups into SpanGroups (with no spans because we just care about saving the boxes here, and calling .annotate with the original box_groups is not necessary).
`tt verify -c src/ai2_internal/config.yaml -v bibentry_detection_predictor` passes
todo:
=> Bib detector entity like output

pyproject.toml, src/mmda/utils/tools.py
This is an optimization PR, and like all optimizations,
it makes the code more confusing, I think. My apologies.
MergeSpans has a quadratic component that bites
us very hard in certain circumstances, like automatically
converting BoxGroups to SpanGroups. It is also a critical
dependency in @comorado 's new tables/figures predictor.
This changeset replaces the nested for-loops in python
with a series of operations against numpy matrices to
the same end effect. Using `tt profile` and a dataset built
from SPP API, I measured a >50% reduction in execution
time.
Note: it is possible to get this down to n*lgn for the special
case of `tokens`, since we have the ncls indices on `doc`.
However, this yielded only marginal benefits for the worst `n`s
we're seeing, and performed slightly worse …
=> Speed up merge spans

pyproject.toml, src/ai2_internal/bibentry_detection_predictor/interface.py
follow up to https://github.com/allenai/mmda/pull/232 
after plugging in to SPP discovered citation-linker 500s caused by SpanGroups missing IDs
=> bibdetector - give both outputs ids at SpanGroup level

pyproject.toml, src/mmda/featurizers/citation_link_featurizers.py
When `source_text` is a list of tokens make sure to join them with a space. We weren't doing this which caused the model to see citation text like: `Krawczyketal.2013` which is not that kind of data the model was trained on.
I also join `target_text` with a space, but I havent seen a case where it is a list of length longer than 1.
=> join symbols in source_text using a space

pyproject.toml
Bib entry predictor is failing its integration tests because
`detectron2` depends on a deprecated `PIL.Image` 
interpolation mode that was removed over the weekend.
This version bounds `Pillow<10` to fix.
=> Fix pil issue

pyproject.toml, src/ai2_internal/bibentry_predictor_mmda/interface.py, src/mmda/predictors/hf_predictors/bibentry_predictor/predictor.py
Limits vram utilization by batching number
of bibentries that are passed to model at one
time (previously unbounded).
Context: our TIMO endpoint is running out of
GPU memory very quickly with production traffic
pointed at it. It is normal for these models to increase
vram usage to some plateau while they are warming
up, but the degree to which this was happening was
excessive.
I pulled a paper with >100 references
and ran it against a couple ad hoc endpoints. One
without bibentry batching, and one with the default
batching implemented here (n=5). Each had a single
worker. The latter showed far lower vram and gpu core utilization,
and had inference times twice as fast to boot. Moreover,
the unbatched instance's vram plateaued at ~60% with 
just a single gunicorn worker, explaining why prod …
=> Memory fixes for bibentry predictor.

pyproject.toml, src/mmda/predictors/hf_predictors/mention_predictor.py
Unbounded input sizes (within a page) were 
being sent to the GPU for inference. This changeset
forces a constrained batch size of 512 tokens.
Context: the citation mentions TIMO endpoint
has been suffering since pointing SPP prod at
it. Broadly it shows very high vram utilization
that is not solved by reducing worker count
per machine, and very high inference times. Both
these things were seen as well in the bibentry detector,
resolved with a similar patch.
Unlike that model, however, I was not able to
reproduce memory spikes in a test setting with
real papers, likely due to the relative rarity of papers
with excessive numbers of tokens on individual pages.
The issue was reproducible, however, by fabricating
some pathological data and sending that to test
servers. Seen below, the first …
=> constrain vram utilization in citation mentions

pyproject.toml, src/mmda/predictors/sklearn_predictors/svm_word_predictor.py
In PDF `585bcfc650f744efa7942900b742c1b64863350e`
Resolving this issue:
```
Traceback (most recent call last):
File "/opt/ml/code/server/api.py", line 329, in perform_invocations
prediction_batch = maybe_predictor.predict_batch(batch)
File "/usr/local/lib/python3.10/site-packages/ai2_internal/svm_word_predictor/interface.py", line 73, in predict_batch
return [self.predict_one(instance) for instance in instances]
File "/usr/local/lib/python3.10/site-packages/ai2_internal/svm_word_predictor/interface.py", line 73, in <listcomp>
return [self.predict_one(instance) for instance in instances]
File "/usr/local/lib/python3.10/site-packages/ai2_internal/svm_word_predictor/interface.py", line 56, in predict_one
words = self._predictor.predict(doc)
File …
```
=> bugfix; not sure why but skipping token IDs in some pdfs

pyproject.toml, src/mmda/predictors/hf_predictors/mention_predictor.py
We were leaving the label predictions tensors on the GPU,
which was leading to lots of expensive GPU calls to read
the data. In particular, `tt profile` revealed the following:
Scalene's GPU time reporting is generally full of false attribution,
but it was a hint in the right direction in this case.
Based on my interpretation of the code, we were being forced
to access this tensor off the GPU three times for _every_ input
word in the document.
After pulling the label preds into system memory:
I confirmed the remaining high GPU items reported by the
profiler have nothing to do with the GPU, 
and the code is too scary to futz about with anyway.
=> dramatically improve citation mentions predictor perf

pyproject.toml, src/ai2_internal/bibentry_detection_predictor/interface.py, src/mmda/predictors/d2_predictors/bibentry_detection_predictor.py
Fixes bibentry detector issue with orphaned boxes
RE: https://github.com/allenai/scholar/issues/35308
Sometimes the detector predicts boxes that don't intersect
any tokens on the page. In these cases we should discard
the box, as it doesn't map to text and causes a runtime error
otherwise.
=> Bib detector fixes

pyproject.toml, src/mmda/parsers/grobid_augment_existing_document_parser.py
makes converting empty `coords` string failproof (fix for error type 1 that was showing up with some bib refs in https://github.com/allenai/scholar/issues/37426)
todo:
=> grobid augmenter parser: don't fail with bad coords

pyproject.toml, src/mmda/utils/tools.py
Solution for https://github.com/allenai/scholar/issues/38452
The problem was in running `box_groups_to_span_groups` with `center=True`. We want to keep `center=True` because it allows us to get good texts in most cases when converting from Grobid box groups to MMDA spangroups. However in some cases it was causing a problem.
The overlapping spangroups error seen from spp-grobid was always a single character span found in 2 different spangroups. This was due to single character tokens that were sometimes not found to be overlapping with the box when running `allocate_overlapping_tokens_for_box`, but then got swallowed up with MergeSpans, and we weren't accounting for this. We now update the dictionary containing the remaining allocatable tokens _after_ …
=> Fix for sg overlap error in box_groups_to_span_groups when center=true

pyproject.toml, src/mmda/utils/tools.py
this is a bug fix for an error made in https://github.com/allenai/mmda/pull/276
It's possible to find tokens from the original Document overlapping with the MergedSpan SpanGroup that are already allocated to a different SpanGroup, so we need to check first if it's in the list of available tokens before attempting to remove it. 
todo:
=> bugfix for box_groups_to_span_groups when center=True

pyproject.toml
v4.34.0 release did a complete refactor of the tokenizer module, see:
https://github.com/huggingface/transformers/pull/23909
Something about the difference is causing vila to
produce literally billions of lines of log warning messages to Datadog in prod. 
I don't know if these warnings are meaningful, but they are expensive.
Example logs:
https://app.datadoghq.com/logs?query=service%3Avila-v0%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=paused&stream_sort=desc&viz=stream&from_ts=1697556761689&to_ts=1697557153857&live=false
=> Caps max allowed version of transformers for vila.

pyproject.toml, src/mmda/parsers/grobid_augment_existing_document_parser.py, src/mmda/utils/tools.py
Solution to https://github.com/allenai/scholar/issues/38452 
Refactored the way Grobid sections/paragraphs/sentences are annotated onto the doc to reduce SpanGroup overlap errors
This involved refactoring the "sections" section of the code to only generate spangroups from sentences and headings (since those are the boxgroups Grobid provides) and using tuples of [optional[heading], [list of paragraphs[list of sentences]]] to make the hierarchical section/paragraph spangroups instead of trying to make huge box lists for each piece as originally written. This made it easier to pinpoint the source of SpanGroup overlap errors.
A necessary update was to make _box_groups_to_span_groups keep track of which tokens were already allocated in previous sentences, since we loop through by Grobid …
=> Refactor grobid sections

pyproject.toml, src/mmda/parsers/grobid_augment_existing_document_parser.py
For https://github.com/allenai/scholar/issues/38452 and https://github.com/allenai/scholar/issues/39910
This fixes a bug that was resulting in sections that had paragraphs but no sentences, which resulted in an error in pipeline-elements in SPP.
**then** (from initial investigation notes in https://github.com/allenai/scholar/issues/38452#issuecomment-1821935080) -- section id 4 has a paragraph but no sentences (paragraphs come from sentences so this didn't make sense):
The problem was in the python control flow where paragraphs were being added to even if we weren't adding the sentences (due to the sentence text already being claimed by the previous duplicate section -- due to it being a weird PDF and Grobid giving double sections -- more details on that under "continued investigation …
=> grobid augmenter - fix Sections-Paragraphs bug

pyproject.toml, src/ai2_internal/api.py, src/mmda/featurizers/citation_link_featurizers.py
Some applications wants to use pydantic2
but have been blocked by strict constraint on
pydantic1 in mmda. This changeset allows the
basic library to be used with either major
version (but preserves the 1.x requirement
for specific models so as not to break anything
in S2's SPP pipeline).
=> Allows use of pydantic 2 by dependents.
